#!/usr/bin/env bash
# Build the active mechanism-and-boundary manuscript with the official TMLR
# submission style. This document-only operation does not run models,
# experiments, evaluators, or access held-out/test data.

set -euo pipefail

usage() {
  cat <<'EOF'
usage: scripts/build_tmlr_paper.sh [--prepare-only] [--refresh-cache]

Generates paper/build/tmlr/main.tex from paper/main.tex, using the official
TMLR style repository pinned below, then builds paper/build/tmlr/tmlr.pdf.

Options:
  --prepare-only   Generate source and style files without invoking latexmk.
  --refresh-cache  Delete and refetch only the generated style cache.
EOF
}

prepare_only=0
refresh_cache=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prepare-only) prepare_only=1 ;;
    --refresh-cache) refresh_cache=1 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
paper_dir="${repo_root}/paper"
source_tex="${paper_dir}/main.tex"
appendix_tex="${paper_dir}/appendix.tex"
output_dir="${paper_dir}/build/tmlr"
style_cache="${paper_dir}/build/tmlr-style-source"
style_repo="https://github.com/JmlrOrg/tmlr-style-file.git"
style_commit="7bf90efe3a0debbba703c05c43f3ff7e4d4a2992"

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    echo "neither shasum nor sha256sum is available" >&2
    return 1
  fi
}

if [[ ! -f "${source_tex}" ]]; then
  echo "missing manuscript source: ${source_tex}" >&2
  exit 1
fi
if [[ ! -f "${appendix_tex}" ]]; then
  echo "missing TMLR appendix source: ${appendix_tex}" >&2
  exit 1
fi

if [[ "${refresh_cache}" == "1" ]]; then
  rm -rf -- "${style_cache}"
fi
mkdir -p "${output_dir}"

if [[ ! -d "${style_cache}/.git" ]]; then
  git clone --quiet --no-checkout "${style_repo}" "${style_cache}"
fi
if ! git -C "${style_cache}" cat-file -e "${style_commit}^{commit}" 2>/dev/null; then
  git -C "${style_cache}" fetch --quiet origin main
fi
git -C "${style_cache}" checkout --quiet --detach "${style_commit}"

actual_commit="$(git -C "${style_cache}" rev-parse HEAD)"
if [[ "${actual_commit}" != "${style_commit}" ]]; then
  echo "TMLR style commit mismatch: ${actual_commit} != ${style_commit}" >&2
  exit 1
fi

for file in tmlr.sty tmlr.bst fancyhdr.sty LICENSE; do
  if [[ ! -f "${style_cache}/${file}" ]]; then
    echo "pinned TMLR style is missing ${file}" >&2
    exit 1
  fi
  install -m 0644 "${style_cache}/${file}" "${output_dir}/${file}"
done

generated_tex="${output_dir}/main.tex"
{
  cat <<'EOF'
% Generated by scripts/build_tmlr_paper.sh. Do not edit this file directly.
% The scientific body comes from paper/main.tex; only the venue shell changes.
\documentclass[10pt]{article}
\usepackage{tmlr}
\usepackage[hyphens]{url}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{hyperref}
\hypersetup{hidelinks}

\title{When Does Typed Conflict Control Help? Falsification-Guided Retrieval and Its Observed Boundaries}

% Submission mode hides this placeholder and prints an anonymous title block.
% Real author metadata is added only after acceptance.
\author{\name Anonymous Author \email anonymous@example.invalid \\
  \addr Anonymous institution}

\def\month{MM}
\def\year{YYYY}
\def\openreview{\url{https://openreview.net/forum?id=XXXX}}
EOF

  awk '
    BEGIN { body = 0 }
    /^\\begin\{document\}$/ { body = 1 }
    body {
      if ($0 == "\\bibliography{references}") {
        print "\\appendix"
        print "\\input{appendix}"
        print "\\bibliographystyle{tmlr}"
      }
      print
    }
  ' "${source_tex}"
} >"${generated_tex}"

cat >"${output_dir}/SOURCE.lock" <<EOF
source=paper/main.tex
source_sha256=$(sha256_file "${source_tex}")
appendix=paper/appendix.tex
appendix_sha256=$(sha256_file "${appendix_tex}")
style_repository=${style_repo}
style_commit=${style_commit}
mode=anonymous_submission
EOF

if [[ "${prepare_only}" == "1" ]]; then
  echo "prepared=${generated_tex}"
  echo "style_commit=${style_commit}"
  exit 0
fi

if ! command -v latexmk >/dev/null 2>&1; then
  echo "latexmk is required; use --prepare-only when TeX is unavailable" >&2
  exit 1
fi

output_rel="build/tmlr"
(
  cd "${paper_dir}"
  TEXINPUTS="${output_dir}:" BSTINPUTS="${output_dir}:" \
    latexmk -pdf -interaction=nonstopmode -halt-on-error \
      -g -outdir="${output_rel}" -jobname=tmlr "${output_rel}/main.tex"
)

pdf="${output_dir}/tmlr.pdf"
if [[ ! -s "${pdf}" ]]; then
  echo "TMLR PDF was not produced: ${pdf}" >&2
  exit 1
fi

log="${output_dir}/tmlr.log"
if [[ ! -f "${log}" ]]; then
  echo "TMLR build log was not produced: ${log}" >&2
  exit 1
fi
if grep -Eqi 'Overfull \\hbox|LaTeX Warning:.*undefined|There were undefined references|Citation .* undefined' "${log}"; then
  echo "TMLR build contains a layout overflow or unresolved reference:" >&2
  grep -Ein 'Overfull \\hbox|LaTeX Warning:.*undefined|There were undefined references|Citation .* undefined' "${log}" >&2
  exit 1
fi

echo "pdf=${pdf}"
echo "style_commit=${style_commit}"
echo "source_sha256=$(sha256_file "${source_tex}")"
echo "appendix_sha256=$(sha256_file "${appendix_tex}")"
